add_newline = false

[git_status]
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count} ⇣${behind_count} "
behind = "⇣${count} "

untracked = '[\($count\) ](blue)'
stashed = '[\($count\) ](blue)'
modified = '[\($count\) ](yellow)'
staged = '[\($count\) ](green)'
renamed = '[\($count\) ](yellow)'
deleted = '[\($count\) ](red)'
