require "mcprisk.functions"

require "mcprisk.autocommands"
require "mcprisk.cmp"
require "mcprisk.colorscheme"
require "mcprisk.comment"
require "mcprisk.keybindings"
require "mcprisk.lsp"
require "mcprisk.options"
require "mcprisk.plugins"
require "mcprisk.telescope"
require "mcprisk.treesitter"
